# Generated by Django 5.0.6 on 2024-05-13 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=200)),
                ("explanation", models.TextField()),
                ("url", models.URLField()),
                ("hdurl", models.URLField()),
                ("media_type", models.CharField(max_length=10)),
                ("service_version", models.CharField(max_length=10)),
                ("copyright", models.CharField(max_length=200)),
            ],
        ),
    ]
