# Generated by Django 5.0.6 on 2024-05-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_picture_additional_data_alter_picture_copyright_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='resource',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
